const command: SypherAI.Command = {
  name: "relapse",
  role: 1,
  usage: "relapse",
  author: "Francis Loyd Raval",
  aliases: ["relapsing", "r"],
  cooldowns: 30,
  description: "Spams a heartfelt Filipino relapse message, 1 second per line",

  async onCall({ response }) {
    const lines = [
      "Na para bang...",
      "ginawa mo na ang lahat",
      "ngunit di parin sya napa sayo",
      "kahit ilang beses mo na sinubukan",
      "kahit ilang luha na ang natuyo",
      "kahit ilang gabi kang di nakatulog",
      "sa pag-iisip kung paano sya mababawi",
      "pero sa huli...",
      "ikaw parin ang talo",
      "ikaw parin ang nasasaktan",
      "habang sya...",
      "masaya na sa iba",
      "at ikaw?",
      "nandito ka pa rin",
      "naghihintay",
      "na baka sakali",
      "na baka bukas",
      "na baka kahit kailan...",
      "pero alam mo sa sarili mo",
      "na wala nang balikan",
      "na tapos na",
      "na kailangan mo nang mag move on",
      "pero bakit...",
      "bakit parang di mo magawa?",
      "bakit parang ikaw na lang?",
      "bakit parang ikaw na lang ang nahihirapan?",
      "pero teka...",
      "huminga ka muna",
      "oo, ikaw yan",
      "huminga ka",
      "kasi buhay ka pa",
      "at kahit masakit",
      "kahit mahirap",
      "kahit parang ayaw mo na",
      "may bukas pa",
      "may bagong umaga",
      "may bagong simula",
      "at isang araw...",
      "makakalimutan mo rin sya",
      "isang araw...",
      "makakahanap ka ng iba",
      "isang araw...",
      "magiging ikaw na ulit",
      "pero sa ngayon...",
      "pahinga ka muna",
      "iyak mo na yan",
      "hayaan mo",
      "kasi okay lang",
      "kasi tao ka",
      "kasi mahal mo sya",
      "pero mas mahalaga...",
      "ang sarili mo",
      "at darating ang araw",
      "na magpapasalamat ka",
      "na di ka nya pinili",
      "kasi deserve mo ng mas higit pa",
      "deserve mo ng tunay",
      "deserve mo ng...",
      "ikaw."
    ];

    for (const line of lines) {
      await response.send(line);
      await new Promise(resolve => setTimeout(resolve, 1000));
    }
  },
};

export default command;
