export const darkJokes = [
  "A man with no arms walks into a bar. The bartender says, 'We don’t serve your kind here.' He replies, 'Good, I can’t pay anyway.'",
  "She gave birth in a graveyard. The baby came out already buried in family expectations.",
  "He lost both legs in the war. Now he fights every day just to stand up for himself.",
  "Her heart stopped at 3:07 AM. The clock kept ticking. It had places to be.",
  "They found his body in the freezer. He always said he wanted to be cool when he died.",
  "The orphan asked for parents. Santa left coal. At least it was warm.",
  "He swallowed bleach to clean his soul. It worked. Nothing was left.",
  "She cut off her ears to stop hearing her mother’s voice. The silence screamed louder.",
  "The blind man read her suicide note in Braille. He laughed. It was the only way he knew how.",
  "He jumped off the bridge holding his regrets. They floated. He didn’t.",
  "The cancer patient smiled at chemo. 'Finally,' he said, 'something that hates me more than I do.'",
  "She starved herself to be beautiful. The mirror still lied. So did the scale.",
  "His therapist ghosted him. Even mental health couldn’t handle his baggage.",
  "The mute girl screamed in her sleep. No one heard. No one ever did.",
  "He set himself on fire to feel something. The flames were disappointed.",
  "She drowned her sorrows in vodka. They learned to swim.",
  "The paralyzed man dreamed of running. His legs filed a restraining order.",
  "He ate glass to feel something sharp inside. The pain was familiar.",
  "She married her rapist. The priest said, 'Till death do us part.' She took it literally.",
  "The amputee won the lottery. Bought new legs. Still couldn’t walk away from his past.",
  "He hung himself with his seatbelt. Safety first.",
  "She buried her child alive in her heart. It still cries at night.",
  "The soldier came home without arms. His daughter asked, 'Can you still hug me?' He tried.",
  "He overdosed on antidepressants. Died happy. For once.",
  "She slit her wrists in the bathtub. The water turned pink. So did her dreams.",
  "The deaf composer wrote his suicide symphony. No one clapped.",
  "He burned his family photos. The ashes looked just like them.",
  "She swallowed pills like compliments. Still felt empty.",
  "The man with no face smiled anyway. No one noticed the difference.",
  "He stabbed his reflection. The mirror bled. He didn’t.",
  "She gave her kidney to her abusive husband. He sold it for drugs.",
  "The child drew a family portrait. Everyone had X’s for eyes.",
  "He choked on his own laughter. The joke was on him.",
  "She froze to death waiting for a text back.",
  "The veteran saluted his missing arm. Old habits die hard.",
  "He carved 'HELP' into his skin. The scars spelled 'HOPE' backward.",
  "She jumped from the 13th floor. Landed on her feet. In hell.",
  "The insomniac counted sheep. They all had his face. They all jumped the fence.",
  "He ate his feelings. Gained 300 pounds of regret.",
  "She tattooed 'LOVE' on her wrists. Covered the scars. Not the memory.",
  "The clown died laughing. The audience thought it was part of the act.",
  "He proposed with a noose. She said yes. They both hung in there.",
  "She lost her voice screaming for help. Found it again in therapy. No one listened.",
  "The firefighter burned alive saving a cat. The cat survived. It never thanked him.",
  "He drank himself to death. The bottle was half full. So was he.",
  "She cut her tongue out to stop lying. The truth still bled.",
  "The pilot crashed into the ocean. His last words: 'I just wanted to fly.'",
  "He sold his soul for a sandwich. It was stale.",
  "She wore black to her own wedding. The groom never showed. The dress fit perfectly.",
  "The surgeon removed his own heart. Said it was in the way.",
  "He laughed at funerals. Cried at birthdays. Got the order wrong.",
  "She swallowed fire to warm her soul. Burned from the inside out.",
  "The writer killed his characters. They came back as typos.",
  "He dug his own grave. Took a nap. Woke up buried in debt.",
  "She smiled through the pain. Her teeth fell out one by one.",
  "The chef cooked his fingers. Said they tasted like home.",
  "He ran from his shadow. It caught up at sunset.",
  "She planted seeds of hope. Grew a forest of nooses.",
  "The musician went deaf. The silence composed his best work.",
  "He built a house of cards. Lived in it. Died in the collapse.",
  "She collected tears in a jar. Drank them when thirsty.",
  "The artist painted with blood. The canvas screamed.",
  "He mailed his heart to his ex. Return to sender. Insufficient postage.",
  "She danced on her father’s grave. The dirt was still warm.",
  "The clock stopped at 3:33. Time died. So did he.",
  "He whispered secrets to the wind. It told everyone.",
  "She fed her nightmares to the dog. It starved.",
  "The mirror cracked from shame. She glued it back. Still broken.",
  "He swallowed a star. Burned a hole through his chest.",
  "She wrote 'I’m fine' in blood. The paper absorbed it.",
  "The child asked why the sky was blue. The clouds cried.",
  "He sold his eyes for a better view. Saw nothing.",
  "She hugged a cactus. Said it felt like family.",
  "The poet rhymed pain with again. Again. Again.",
  "He jumped into the void. It pushed him back. Not welcome.",
  "She kissed a blade. It kissed back. Deeper.",
  "The candle burned at both ends. So did she.",
  "He spoke to God. Got voicemail.",
  "She buried her smile. It grew teeth.",
  "The orphan built a snowman. It melted. So did hope.",
  "He wore his trauma like cologne. Everyone smelled it.",
  "She laughed until she cried. Then kept laughing.",
  "The grave digger quit. Said the dead were better company.",
  "He ate the forbidden fruit. It tasted like childhood.",
  "She stitched her mouth shut. The screams came out her eyes.",
  "The king lost his crown. Found it in the toilet.",
  "He flew too close to the sun. Got a tan. And cancer.",
  "She watered dead flowers. They bloomed in her nightmares.",
  "The jester told the truth. The king had him beheaded.",
  "He counted blessings. Ran out of fingers.",
  "She screamed into pillows. They absorbed the sound. Not the pain.",
  "The lighthouse went dark. Ships still crashed.",
  "He built walls around his heart. Bricked in the pain.",
  "She sang lullabies to her demons. They fell asleep. She didn’t.",
  "The rain washed away footprints. Not memories.",
  "He chased happiness. It filed a restraining order.",
  "She collected broken glass. Called it art.",
  "The wolf wore sheep’s clothing. The sheep unionized.",
  "He swallowed pride. Choked on it.",
  "She danced with death. He stepped on her toes.",
  "The book of life had blank pages. She wrote in blood.",
  "He smiled in photos. Cried in mirrors.",
  "She planted lies. Harvested loneliness.",
  "The sun set on his dreams. Never rose.",
  "He held his breath underwater. Time stopped. So did he.",
  "She mailed apologies. They came back unopened.",
  "The bridge burned behind him. No way back. No way forward.",
  "He carved his name into a tree. It died.",
  "She wore grief like makeup. It never smudged.",
  "The clock laughed. Time was a joke.",
  "He fed his fears to the fire. They grew wings.",
  "She whispered 'stay' to the wind. It left.",
  "The stars fell. No one made a wish.",
  "He built a throne of bones. Sat alone.",
  "She cried diamonds. Still broke.",
  "The moon hid. Even it couldn’t watch.",
  "He sold tomorrow for today. Got scammed.",
  "She hugged her shadow. It walked away.",
  "The river ran red. Memories drowned.",
  "He screamed at the void. It screamed back in his voice.",
  "She buried her past. It dug itself up.",
  "The door closed. No knob on the inside.",
  "He lit a match in the dark. Burned his fingers.",
  "She wrote love letters to no one. Got replies from herself.",
  "The sky cracked. God peeked through. Looked away.",
  "He jumped. The ground caught him. Too hard.",
  "She smiled at the abyss. It smiled back. With teeth.",
  "The end came quietly. No one noticed.",
  "He asked for mercy. Got silence.",
  "She forgave. Never forgot.",
  "The light at the end was a train.",
  "He waved goodbye with a hand that wasn’t there.",
  "She said 'I’m okay.' The lie weighed 300 pounds.",
  "The joke wrote itself. No one laughed.",
  "He died standing up. Gravity finally won.",
  "She lived in reverse. Born old. Died young.",
  "The punchline came after death.",
  "He asked the mirror who he was. It shattered.",
  "She planted a kiss on his cold lips. Got frostbite.",
  "The story ended mid-sentence.",
  "He laughed until his heart stopped. It was funny.",
  "She cried until her eyes dried. Then kept crying.",
  "The dark wasn’t afraid. It was home.",
  "He reached for the stars. Grabbed smoke.",
  "She whispered 'forever.' Echoed once. Then nothing.",
  "The joke was life. The punchline: death.",
  "He waved at the person across the room. No arms. No response."
];