export const relapseCategories = {
  torpe: [
    "What if...",
    "Niligawan ko siya in the first place?",
    "Kaso huli na ang lahat..",
    "May nauna na sa akin..",
    "Dahil sa katorpehan kong to..",
    "Hindi ko sinabi agad.",
    "Natakot ako sa 'no'.",
    "Nag-overthink ako ng sobra.",
    "Hinintay ko ang 'tamang oras'.",
    "Pero wala nang oras.",
    "Naunahan na ako.",
    "Nakita ko silang magkasama.",
    "Ngumiti siya sa iba.",
    "Tumawa siya sa joke niya.",
    "Hinawakan niya ang kamay niya.",
    "At ako?",
    "Nandito lang sa sulok.",
    "Nagpapanggap na okay lang.",
    "Pero nasasaktan.",
    "Nagsisisi.",
    "Naghihintay pa rin.",
    "Sa wala.",
    "Sa alaala niya.",
    "Na hindi na babalik.",
    "Sa tingin niya sa iba.",
    "Sa ngiti niya sa iba.",
    "Sa yakap niya sa iba.",
    "Sa halik niya sa iba.",
    "Sa plano nila sa iba.",
    "Sa kinabukasan nila.",
    "At ako?",
    "Nasa labas.",
    "Naghihintay ng himala.",
    "Naghihintay ng sagot.",
    "Naghihintay ng pagkakataon.",
    "Na hindi na darating.",
    "Kasi hindi niya ako nakikita.",
    "Hindi niya ako napapansin.",
    "Hindi niya ako iniisip.",
    "Hindi niya ako mahal.",
    "At ako?",
    "Mahal na mahal siya.",
    "Kahit hindi niya alam.",
    "Kahit hindi niya nararamdaman.",
    "Kahit hindi niya nakikita.",
    "Kahit hindi niya naiintindihan.",
    "Kahit hindi niya naririnig.",
    "Kahit hindi niya nararamdaman.",
    "Kahit hindi niya nakikita.",
    "Kahit hindi niya naririnig.",
    "Kahit hindi niya naiintindihan.",
    "Kahit hindi niya alam.",
    "Kahit hindi niya nakikita.",
    "Kahit hindi niya naririnig.",
    "Kahit hindi niya naiintindihan.",
    "Kahit hindi niya alam.",
    "Kahit hindi niya nakikita.",
    "Kahit hindi niya naririnig.",
    "Kahit hindi niya naiintindihan.",
    "At ako?",
    "Nandito pa rin."
  ],

  movingon: [
    "Matagal nang tapos...",
    "pero ikaw pa rin.",
    "Naghihintay sa wala.",
    "Umaasa sa imposible.",
    "Pero hindi na babalik.",
    "Kailangan mo nang bitawan.",
    "Deserve mo ng mas higit pa.",
    "Huminga ka muna.",
    "Oo, ikaw yan.",
    "Buhay ka pa.",
    "May bukas pa.",
    "May bagong umaga.",
    "May bagong simula.",
    "Isang araw...",
    "makakalimutan mo siya.",
    "Isang araw...",
    "magiging ikaw ulit.",
    "At magpapasalamat ka...",
    "na hindi ka niya pinili.",
    "Kasi deserve mo ng tunay.",
    "Hindi yung nagpapanggap.",
    "Hindi yung pansamantala.",
    "Hindi yung 'kung pwede lang'.",
    "Deserve mo ng...",
    "ikaw.",
    "Buong-buo.",
    "Hindi durog.",
    "Hindi naghihintay.",
    "Hindi umaasa.",
    "Ikaw na.",
    "Malakas.",
    "Matapang.",
    "Malaya.",
    "Hindi nakatali.",
    "Hindi nakakulong.",
    "Hindi nasasaktan.",
    "Hindi nahihirapan.",
    "Hindi nag-iisa.",
    "Hindi nawawala.",
    "Hindi nalilito.",
    "Hindi natatakot.",
    "Hindi nagsisisi.",
    "Hindi nagdududa.",
    "Hindi nag-aalangan.",
    "Hindi naghihintay.",
    "Hindi umaasa.",
    "Hindi nahihirapan.",
    "Hindi nasasaktan.",
    "Hindi nag-iisa.",
    "Hindi nawawala.",
    "Hindi nalilito.",
    "Hindi natatakot.",
    "Hindi nagsisisi.",
    "Hindi nagdududa.",
    "Hindi nag-aalangan.",
    "Hindi naghihintay.",
    "Hindi umaasa.",
    "Hindi nahihirapan.",
    "Hindi nasasaktan.",
    "Hindi nag-iisa.",
    "At ikaw?",
    "Ikaw na."
  ],

  breakup: [
    "Na para bang...",
    "ginawa mo na ang lahat",
    "ngunit di parin sya napa sayo",
    "kahit ilang beses mo na sinubukan",
    "kahit ilang luha na ang natuyo",
    "kahit ilang gabi kang di nakatulog",
    "sa pag-iisip kung paano sya mababawi",
    "pero sa huli...",
    "ikaw parin ang talo",
    "ikaw parin ang nasasaktan",
    "habang sya...",
    "masaya na sa iba",
    "at ikaw?",
    "nandito ka pa rin",
    "naghihintay",
    "na baka sakali",
    "na baka bukas",
    "na baka kahit kailan...",
    "pero alam mo sa sarili mo",
    "na wala nang balikan",
    "na tapos na",
    "na kailangan mo nang mag move on",
    "pero bakit...",
    "bakit parang di mo magawa?",
    "bakit parang ikaw na lang?",
    "bakit parang ikaw na lang ang nahihirapan?",
    "pero teka...",
    "huminga ka muna",
    "oo, ikaw yan",
    "huminga ka",
    "kasi buhay ka pa",
    "at kahit masakit",
    "kahit mahirap",
    "kahit parang ayaw mo na",
    "may bukas pa",
    "may bagong umaga",
    "may bagong simula",
    "at isang araw...",
    "makakalimutan mo rin sya",
    "isang araw...",
    "makakahanap ka ng iba",
    "isang araw...",
    "magiging ikaw na ulit",
    "pero sa ngayon...",
    "pahinga ka muna",
    "iyak mo na yan",
    "hayaan mo",
    "kasi okay lang",
    "kasi tao ka",
    "kasi mahal mo sya",
    "pero mas mahalaga...",
    "ang sarili mo",
    "at darating ang araw",
    "na magpapasalamat ka",
    "na di ka nya pinili",
    "kasi deserve mo ng mas higit pa",
    "deserve mo ng tunay",
    "deserve mo ng...",
    "ikaw.",
    "Buong-buo.",
    "Malakas.",
    "Matapang."
  ],

  ghosting: [
    "Parang bigla na lang...",
    "nawala ang chat niya.",
    "wala nang 'seen'.",
    "wala nang reply.",
    "wala nang 'typing...'.",
    "wala nang good morning.",
    "wala nang good night.",
    "wala nang kwento.",
    "wala nang tawanan.",
    "wala nang 'kumain ka na?'.",
    "wala nang 'ingat ka'.",
    "wala nang 'miss you'.",
    "wala nang 'sorry'.",
    "wala nang 'okay lang'.",
    "wala nang 'mahal kita'.",
    "wala nang lahat.",
    "parang hindi kayo nagkausap.",
    "parang hindi kayo nagkakilala.",
    "parang hindi kayo naging tayo.",
    "parang hindi kayo naging close.",
    "parang hindi kayo naging magkaibigan.",
    "parang hindi kayo naging importante.",
    "parang hindi kayo naging totoo.",
    "parang hindi kayo naging real.",
    "parang hindi kayo naging tayo.",
    "parang hindi kayo naging magkasama.",
    "parang hindi kayo naging masaya.",
    "parang hindi kayo naging buo.",
    "parang hindi kayo naging perfect.",
    "parang hindi kayo naging forever.",
    "parang hindi kayo naging anything.",
    "at ikaw?",
    "naghihintay pa rin.",
    "nagtetext pa rin.",
    "nagchecheck pa rin.",
    "nag-oopen pa rin.",
    "nag-iisa pa rin.",
    "naghihintay pa rin.",
    "sa wala.",
    "sa 'seen'.",
    "sa 'typing...'.",
    "sa 'online'.",
    "sa 'last seen'.",
    "sa 'active 5 mins ago'.",
    "sa 'active now'.",
    "pero hindi ka niya pinapansin.",
    "hindi ka niya binabasa.",
    "hindi ka niya iniisip.",
    "hindi ka niya naririnig.",
    "hindi ka niya nakikita.",
    "hindi ka niya mahal.",
    "at ikaw?",
    "mahal na mahal siya.",
    "kahit wala na.",
    "kahit hindi na.",
    "kahit hindi na babalik.",
    "At ikaw?",
    "nandito pa rin."
  ]
};