const roasts = [
  "Your momma so fat, when she sits around the house, she sits *around* the house.",
  "Your momma so ugly, even Hello Kitty said goodbye.",
  "Your momma so old, her birth certificate is in Roman numerals.",
  "Your momma so stupid, she thought a quarterback was a refund.",
  "Your momma so lazy, she has a stay-at-home job.",
  "Your dad so bald, I can see what’s on his mind.",
  "Your dad so old, he knew Burger King when he was still a prince.",
  "Your dad so dumb, he thinks a lawsuit is something you wear to court.",
  "Your dad so ugly, when he was born, the doctor slapped your grandma.",
  "You're so fat, even your chair didn't stand a chance.",
  "You're so fat, when you wear high heels, you strike oil.",
  "You're so ugly, your reflection looks away.",
  "You're so stupid, you got locked in a supermarket and starved.",
  "You're so broke, you wash paper plates.",
  "You're so lazy, you got a job at the unemployment office.",
  "You're so old, your social security number is 1.",
  "You're so dumb, you think 'manual labor' is a Mexican guy.",
  "You're the reason the gene pool needs a lifeguard.",
  "You're so fake, even your reflection doesn’t recognize you.",
  "You're so ugly, your mom had to tie a steak around your neck to get the dog to play with you.",
  "You're so stupid, you got hit by a parked car.",
  "You're so broke, your wallet has cobwebs and a 'For Rent' sign.",
  "You're so lazy, you named your bed 'The Office'.",
  "You're so old, you walked into an antique store and they kept you.",
  "You're so ugly, you make blind kids cry.",
  "You're so dumb, you put a ruler next to your bed to see how long you sleep.",
  "You're so fat, your blood type is Ragu.",
  "You're so stupid, you tried to put M&M’s in alphabetical order.",
  "You're so ugly, your birth certificate is an apology letter from the condom factory.",
  "You're so dumb, you think a thesaurus is a dinosaur.",
  "You're so fat, when you skip a meal, the stock market drops.",
  "You're so broke, your idea of a 7-course meal is a hot dog and a six-pack.",
  "You're so old, your childhood toys are in museums.",
  "You're so ugly, you have to sneak up on your mirror.",
  "You're so dumb, you think 'loading' is a city in China.",
  "You're so fat, your belt size is the equator.",
  "You're so stupid, you tried to wake up a computer by yelling 'WAKE UP!'",
  "You're so broke, you use coupons at the dollar store.",
  "You're so lazy, you have a 'Do Not Disturb' sign on your life.",
  "You're so old, you still think 'Netflix and chill' means watching movies.",
  "You're so ugly, your selfies need a trigger warning.",
  "You're so dumb, you think 'innuendo' is Italian for 'suppository'.",
  "You're so fat, you got baptized at Sea World.",
  "You're so stupid, you got locked in a mattress store and slept on the floor.",
  "You're so lazy, you got winded playing chess.",
  "You're so old, your first pet was a dinosaur.",
  "You're so ugly, when you play Mortal Kombat | Scorpion says 'Stay over there.'",
  "You're so fat, you have to iron your pants on the driveway.",
  "You're so stupid, you think 'Bluetooth' is a dental condition.",
  "You're so broke, your credit score is a 'Do Not Resuscitate' order.",
  "You're so lazy, you use a forklift to lift your ego.",
  "You're so old, you knew Gandalf before he had the staff.",
  "You're so ugly, your mirror files a restraining order.",
  "You're so dumb, you think 'RAM' is a male sheep with memory issues.",
  "You're so fat, your waist size is measured in longitude.",
  "You're so stupid, you think '404' is a clothing size.",
  "You're so broke, you use a paperclip as a money clip.",
  "You're so lazy, you got a job as a scarecrow — but even the crows felt sorry for you.",
  "You're so old, your birthstone is lava.",
  "You're so ugly, you make onions cry.",
  "You're so dumb, you think 'GitHub' is where programmers go to party.",
  "You're so fat, you have your own gravitational pull.",
  "You're so stupid, you tried to plug a USB in upside down 47 times.",
  "You're so broke, your bank account has an eviction notice.",
  "You're so lazy, you think 'exercise' is a dirty word.",
  "You're so old, you used to babysit Yoda.",
  "You're so ugly, when you joined an ugly contest, they said 'Sorry, no professionals.'",
  "You're so dumb, you think 'cloud storage' is where rain comes from.",
  "You're so fat, your scale says 'To be continued...'.",
  "You're so stupid, you think 'HTML' is a sexually transmitted disease.",
  "You're so broke, you can’t even afford to go off the grid.",
  "You're so old, you still think 'going viral' means you caught the flu.",
  "You're so ugly, your portraits hang themselves.",
  "You're so dumb, you think 'API' stands for 'A Pretty Idiot'.",
  "You're so fat, you need GPS to find your own feet.",
  "You're so stupid, you think 'Docker' is a pirate’s doctor.",
  "You're so broke, your piggy bank filed for bankruptcy.",
  "You're so lazy, you think 'running late' is a cardio workout.",
  "You're so old, your first computer ran on coal.",
  "You're so ugly, your webcam turns off when you open Zoom.",
  "You're so dumb, you think 'SQL' is pronounced 'squirrel'.",
  "You're so fat, you got stuck in a revolving door.",
  "You're so stupid, you think 'REST API' is a nap for programmers.",
  "You're so broke, you can’t afford to lose.",
  "You're so lazy, you think 'hustle' is a dance move.",
  "You're so old, you remember when 'cloud' just meant rain.",
  "You're so ugly, your face is banned in 17 countries.",
  "You're so dumb, you think 'Git' is a British insult.",
  "You're so fat, you make the Richter scale jealous.",
  "You're so stupid, you think 'microservices' are tiny waiters.",
  "You're so broke, your bank sends you sympathy cards.",
  "You're so lazy, you think 'productivity' is a personality trait.",
  "You're so old, you pre-ordered the Bible.",
  "You're so ugly, your reflection needs therapy.",
  "You're so dumb, you think 'OAuth' is a surprised exclamation.",
  "You're so fat, your shadow needs its own zip code.",
  "You're so stupid, you think 'CI/CD' is a Roman emperor.",
  "You're so broke, you use Monopoly money in real life.",
  "You're so lazy, you think 'motivation' is a myth.",
  "You're so old, you remember when 'viral' meant you needed a doctor.",
  "You're so ugly, your ID photo is a mugshot.",
  "You're so dumb, you think 'DOM' is a character from Fast & Furious.",
  "You're so fat, you have to wear two watches — one for each time zone on your wrist.",
  "You're so stupid, you think 'NoSQL' means 'No, thanks.'",
  "You're so broke, your wallet is on life support.",
  "You're so lazy, you think 'work ethic' is a disease.",
  "You're so old, you used to dial up the internet with a rotary phone.",
  "You're so ugly, your mirror cracked and filed for workers’ comp.",
  "You're so dumb, you think 'JWT' is a new type of weed.",
  "You're so fat, you got arrested for carrying 10 pounds of crack.",
  "You're so stupid, you think 'GraphQL' is a math problem.",
  "You're so broke, you can’t even pay for your own thoughts.",
  "You're so lazy, you think 'ambition' is a four-letter word.",
  "You're so old, you remember when 'selfie' meant taking a picture of yourself in a mirror.",
  "You're so ugly, your face is the reason we have dark mode.",
  "You're so dumb, you think 'Node.js' is a type of tree.",
  "You're so fat, your belt size is measured in astronomy.",
  "You're so stupid, you think 'Firebase' is a lighter for camping.",
  "You're so broke, your idea of wealth is having two-ply toilet paper.",
  "You're so lazy, you think 'rise and grind' is a coffee order.",
  "You're so old, you still think 'Y2K' is coming.",
  "You're so ugly, you make Siri say 'I’m sorry, I can’t help you with that.'",
  "You're so dumb, you think 'MongoDB' is a type of African drum.",
  "You're so fat, you have to use Google Earth to take a selfie.",
  "You're so stupid, you think 'TypeScript' is a new font.",
  "You're so broke, you can’t afford to be offended.",
  "You're so lazy, you think 'hustle culture' is a scam.",
  "You're so old, you remember when 'Bluetooth' was a Viking with dental issues.",
  "You're so ugly, your face is the reason we have screen lock.",
  "You're so dumb, you think 'React' is an emotional response.",
  "You're so fat, you got stuck in a black hole.",
  "You're so stupid, you think 'Vue.js' is French for 'seen it'.",
  "You're so broke, your net worth is a 404 error.",
  "You're so lazy, you think 'grind' is what happens to coffee.",
  "You're so old, you used to ride dinosaurs to school.",
  "You're so ugly, your webcam needs a filter just to function.",
  "You're so dumb, you think 'SaaS' is a snake sound.",
  "You're so fat, your fitness goal is to fit through the door.",
  "You're so stupid, you think 'Agile' is a type of bird.",
  "You're so broke, you can’t even afford to dream.",
  "You're so lazy, you think 'success' is a participation award.",
  "You're so old, you remember when 'streaming' meant fishing.",
  "You're so ugly, your face is the reason we have incognito mode.",
  "You're so dumb, you think 'Kubernetes' is a sneeze in Greek.",
  "You're so fat, you have to grease the doorframe to get in.",
  "You're so stupid, you think 'PaaS' is a dance move.",
  "You're so broke, your bank account is in witness protection.",
  "You're so lazy, you think 'dedication' is a horror movie.",
  "You're so old, you predate the invention of fire.",
  "You're so ugly, your face is the reason we have dark mode on phones.",
  "You're so dumb, you think 'IAM' is a typo for 'I am'.",
  "You're so fat, your scale just says 'One at a time, please.'",
  "You're so stupid, you think 'Lambda' is a Greek letter that codes.",
  "You're so broke, you use a coupon for free air.",
  "You're so lazy, you think 'effort' is a four-letter word.",
  "You're so old, you remember when 'cloud' was just weather.",
  "You're so ugly, your mirror needs therapy.",
  "You're so dumb, you think 'Terraform' is a planet.",
  "You're so fat, you make the sun look small.",
  "You're so stupid, you think 'OpenAPI' is a public bathroom.",
  "You're so broke, your idea of luxury is a working pen.",
  "You're so lazy, you think 'progress' is a myth.",
  "You're so old, you remember when 'online' meant hanging clothes.",
  "You're so ugly, your face is the reason we have password protection.",
  "You're so dumb, you think 'gRPC' is a breakfast cereal.",
  "You're so fat, you have to use a map to navigate your own body.",
  "You're so stupid, you think 'Helm' is a boat accessory for Kubernetes.",
  "You're so broke, you can’t afford to be wrong.",
  "You're so lazy, you think 'action' is a movie genre.",
  "You're so old, you used to ride dinosaurs to school.",
  "You're so ugly, your face is the reason we have face ID.",
  "You're so dumb, you think 'Istio' is a type of pasta.",
  "You're so fat, your shadow needs a diet.",
  "You're so stupid, you think 'Prometheus' is a movie about fire.",
  "You're so broke, your wallet is on food stamps.",
  "You're so lazy, you think 'drive' is a golf term.",
  "You're so old, you remember when 'byte' meant a small bite.",
  "You're so ugly, your face is the reason we have dark mode on everything.",
  "You're so dumb, you think 'Argo' is a Greek boat with YAML.",
  "You're so fat, you make the moon jealous.",
  "You're so stupid, you think 'Vault' is where Batman keeps his secrets.",
  "You're so broke, you can’t even pay for silence.",
  "You're so lazy, you think 'energy' is a drink.",
  "You're so old, you remember when 'firewall' was literal.",
  "You're so ugly, your face is the reason we have screen protectors.",
  "You're so dumb, you think 'Consul' is a diplomat for services.",
  "You're so fat, your belt is a hula hoop with commitment issues.",
  "You're so stupid, you think 'Linkerd' is a social media app.",
  "You're so broke, your bank sends you a 'Get Well Soon' card.",
  "You're so lazy, you think 'momentum' is a physics joke.",
  "You're so old, you remember when 'server' meant a waiter.",
  "You're so ugly, your face is the reason we have password managers.",
  "You're so dumb, you think 'Fluentd' is a language disorder.",
  "You're so fat, you have to use a ladder to put on socks.",
  "You're so stupid, you think 'Jaeger' is a German hunter for traces.",
  "You're so broke, you can’t afford to be average.",
  "You're so lazy, you think 'passion' is a soap opera.",
  "You're so old, you remember when 'cache' was just money.",
  "You're so ugly, your face is the reason we have two-factor authentication.",
  "You're so dumb, you think 'Envoy' is a French diplomat for proxies.",
  "You're so fat, your shadow has stretch marks.",
  "You're so stupid, you think 'Calico' is a cat with policies.",
  "You're so broke, you use a rubber band as a wallet.",
  "You're so lazy, you think 'growth' is a tumor.",
  "You're so old, you remember when 'RAM' was a male sheep.",
  "You're so ugly, your face is the reason we have dark mode on life.",
  "You're so dumb, you think 'Cilium' is a part of the eye with eBPF.",
  "You're so fat, you make the universe expand.",
  "You're so stupid, you think 'Kiali' is a Hawaiian dashboard.",
  "You're so broke, you can’t even afford to be yourself.",
  "You're so lazy, you think 'vision' is a TV setting.",
  "You're so old, you remember when 'download' meant getting off the roof.",
  "You're so ugly, your face is the reason we have face masks.",
  "You're so dumb, you think 'Vitess' is a vitamin for MySQL.",
  "You're so fat, you have to use a boomerang to put on a necklace.",
  "You're so stupid, you think 'Contour' is a makeup brand for Ingress.",
  "You're so broke, your net worth is a 404 page.",
  "You're so lazy, you think 'purpose' is a typo.",
  "You're so old, you remember when 'wireless' meant no strings attached.",
  "You're so ugly, your face is the reason we have privacy settings.",
  "You're so dumb, you think 'Harbor' is a place for container ships.",
  "You're so fat, your scale just says 'Error 404: Weight not found.'",
  "You're so stupid, you think 'Tekton' is a construction company for CI/CD.",
  "You're so broke, you can’t afford to be basic.",
  "You're so lazy, you think 'destiny' is a bus stop.",
  "You're so old, you remember when 'cloud' was just a fluffy thing in the sky.",
  "You're so ugly, your face is the reason we have dark mode on souls.",
  "You're so dumb, you think 'Knative' is a new knitting pattern.",
  "You're so fat, you have to use a satellite to take a full-body photo.",
  "You're so stupid, you think 'ArgoCD' is a music genre.",
  "You're so broke, you can’t even pay for your own funeral.",
  "You're so lazy, you think 'legacy' is a will.",
  "You're so old, you remember when 'streaming' meant crying in public.",
  "You're so ugly, your face is the reason we have face recognition — to avoid you.",
  "You're so dumb, you think 'Flux' is a capacitor for GitOps.",
  "You're so fat, you make the Richter scale look like a mood ring.",
  "You're so stupid, you think 'Thanos' is a Kubernetes operator.",
  "You're so broke, you can’t afford to be human.",
  "You're so lazy, you think 'existence' is a chore.",
  "You're so old, you predate the Big Bang.",
  "You're so ugly, your face is the reason we have dark matter.",
  "You're so dumb, you think 'Chaos Mesh' is a new dance move.",
  "You're so fat, you have your own event horizon.",
  "You're so stupid, you think 'OpenTelemetry' is a new religion.",
  "You're so broke, you can’t even afford to breathe.",
  "You're so lazy, you think 'being' is a full-time job.",
  "You're so old, you remember when 'universe' was just a theory.",
  "You're so ugly, your face is the reason we have black holes.",
  "You're so dumb, you think 'Keda' is a type of cheese for scaling.",
  "You're so fat, you make gravity jealous.",
  "You're so stupid, you think 'Crossplane' is an airplane for infrastructure.",
  "You're so broke, you can’t afford to exist.",
  "You're so lazy, you think 'life' is a participation sport.",
  "You're so old, you remember when 'time' was just a concept.",
  "You're so ugly, your face is the reason we have entropy.",
  "You're so dumb, you think 'Porter' is a luggage service for apps.",
  "You're so fat, you make the speed of light look slow.",
  "You're so stupid, you think 'Volcano' is a spicy Kubernetes tool.",
  "You're so broke, you can’t afford to be alive.",
  "You're so lazy, you think 'reality' is optional.",
  "You're so old, you predate existence.",
  "You're so ugly, your face is the reason we have the heat death of the universe.",
  "You're so dumb, you think 'Brigade' is a military event for scripts.",
  "You're so fat, you make black holes look like diet pills.",
  "You're so stupid, you think 'Skaffold' is a new type of ladder.",
  "You're so broke, you can’t afford to be conscious.",
  "You're so lazy, you think 'thought' is too much effort.",
  "You're so old, you remember when 'nothing' was something.",
  "You're so ugly, your face is the reason we have the end of time.",
  "You're so dumb, you think 'Tilt' is a new dance move for DevOps.",
  "You're so fat, you make the universe look like a snack.",
  "You're so stupid, you think 'Garden' is a Kubernetes flower shop.",
  "You're so broke, you can’t afford to be.",
  "You're so lazy, you think 'zero' is too much.",
  "You're so old, you predate the concept of old.",
  "You're so ugly, your face is the reason we have oblivion.",
  "You're so dumb, you think 'this' is a complete sentence.",
  "You're so fat, you make infinity look finite.",
  "You're so stupid, you think 'end' is just the beginning.",
  "You're so broke, you can’t afford to stop.",
  "You're so lazy, you think 'stop' is a suggestion.",
  "You're so old, you remember when 'forever' was temporary.",
  "You're so ugly, your face is the reason we have the void.",
  "You're so dumb, you think 'roast' is a cooking method.",
  "You're so fat, you make the end look like the beginning.",
  "You're so stupid, you think 'ultimate' is a setting.",
  "You're so broke, you can’t afford to be ultimate.",
  "You're so lazy, you think 'ultimate' is too much effort.",
  "You're so old, you remember when 'ultimate' was just a word.",
  "You're so ugly, your face is the ultimate roast.",
] as const;

export default roasts;