export const timezones = [
  { name: "Afghanistan", tz: "Asia/Kabul" },
  { name: "Albania", tz: "Europe/Tirane" },
  { name: "Algeria", tz: "Africa/Algiers" },
  { name: "Andorra", tz: "Europe/Andorra" },
  { name: "Angola", tz: "Africa/Luanda" },
  { name: "Argentina", tz: "America/Argentina/Buenos_Aires" },
  { name: "Armenia", tz: "Asia/Yerevan" },
  { name: "Australia (Adelaide)", tz: "Australia/Adelaide" },
  { name: "Australia (Brisbane)", tz: "Australia/Brisbane" },
  { name: "Australia (Darwin)", tz: "Australia/Darwin" },
  { name: "Australia (Melbourne)", tz: "Australia/Melbourne" },
  { name: "Australia (Perth)", tz: "Australia/Perth" },
  { name: "Australia (Sydney)", tz: "Australia/Sydney" },
  { name: "Austria", tz: "Europe/Vienna" },
  { name: "Azerbaijan", tz: "Asia/Baku" },
  { name: "Bahamas", tz: "America/Nassau" },
  { name: "Bahrain", tz: "Asia/Bahrain" },
  { name: "Bangladesh", tz: "Asia/Dhaka" },
  { name: "Barbados", tz: "America/Barbados" },
  { name: "Belarus", tz: "Europe/Minsk" },
  { name: "Belgium", tz: "Europe/Brussels" },
  { name: "Belize", tz: "America/Belize" },
  { name: "Bolivia", tz: "America/La_Paz" },
  { name: "Bosnia and Herzegovina", tz: "Europe/Sarajevo" },
  { name: "Botswana", tz: "Africa/Gaborone" },
  { name: "Brazil (Manaus)", tz: "America/Manaus" },
  { name: "Brazil (Recife)", tz: "America/Recife" },
  { name: "Brazil (Rio)", tz: "America/Rio_Branco" },
  { name: "Brazil (São Paulo)", tz: "America/Sao_Paulo" },
  { name: "Brunei", tz: "Asia/Brunei" },
  { name: "Bulgaria", tz: "Europe/Sofia" },
  { name: "Cambodia", tz: "Asia/Phnom_Penh" },
  { name: "Cameroon", tz: "Africa/Douala" },
  { name: "Canada (Calgary)", tz: "America/Edmonton" },
  { name: "Canada (Montreal)", tz: "America/Montreal" },
  { name: "Canada (Toronto)", tz: "America/Toronto" },
  { name: "Canada (Vancouver)", tz: "America/Vancouver" },
  { name: "Canada (Winnipeg)", tz: "America/Winnipeg" },
  { name: "Chile", tz: "America/Santiago" },
  { name: "China (Beijing)", tz: "Asia/Shanghai" },
  { name: "China (Hong Kong)", tz: "Asia/Hong_Kong" },
  { name: "Colombia", tz: "America/Bogota" },
  { name: "Costa Rica", tz: "America/Costa_Rica" },
  { name: "Croatia", tz: "Europe/Zagreb" },
  { name: "Cuba", tz: "America/Havana" },
  { name: "Cyprus", tz: "Asia/Nicosia" },
  { name: "Czech Republic", tz: "Europe/Prague" },
  { name: "Denmark", tz: "Europe/Copenhagen" },
  { name: "Dominican Republic", tz: "America/Santo_Domingo" },
  { name: "Ecuador", tz: "America/Guayaquil" },
  { name: "Egypt", tz: "Africa/Cairo" },
  { name: "El Salvador", tz: "America/El_Salvador" },
  { name: "Estonia", tz: "Europe/Tallinn" },
  { name: "Ethiopia", tz: "Africa/Addis_Ababa" },
  { name: "Fiji", tz: "Pacific/Fiji" },
  { name: "Finland", tz: "Europe/Helsinki" },
  { name: "France", tz: "Europe/Paris" },
  { name: "Georgia", tz: "Asia/Tbilisi" },
  { name: "Germany", tz: "Europe/Berlin" },
  { name: "Ghana", tz: "Africa/Accra" },
  { name: "Greece", tz: "Europe/Athens" },
  { name: "Greenland", tz: "America/Nuuk" },
  { name: "Guatemala", tz: "America/Guatemala" },
  { name: "Honduras", tz: "America/Tegucigalpa" },
  { name: "Hungary", tz: "Europe/Budapest" },
  { name: "Iceland", tz: "Atlantic/Reykjavik" },
  { name: "India", tz: "Asia/Kolkata" },
  { name: "Indonesia (Jakarta)", tz: "Asia/Jakarta" },
  { name: "Indonesia (Makassar)", tz: "Asia/Makassar" },
  { name: "Iran", tz: "Asia/Tehran" },
  { name: "Iraq", tz: "Asia/Baghdad" },
  { name: "Ireland", tz: "Europe/Dublin" },
  { name: "Israel", tz: "Asia/Jerusalem" },
  { name: "Italy", tz: "Europe/Rome" },
  { name: "Jamaica", tz: "America/Jamaica" },
  { name: "Japan", tz: "Asia/Tokyo" },
  { name: "Jordan", tz: "Asia/Amman" },
  { name: "Kazakhstan", tz: "Asia/Almaty" },
  { name: "Kenya", tz: "Africa/Nairobi" },
  { name: "Kuwait", tz: "Asia/Kuwait" },
  { name: "Latvia", tz: "Europe/Riga" },
  { name: "Lebanon", tz: "Asia/Beirut" },
  { name: "Libya", tz: "Africa/Tripoli" },
  { name: "Lithuania", tz: "Europe/Vilnius" },
  { name: "Luxembourg", tz: "Europe/Luxembourg" },
  { name: "Malaysia", tz: "Asia/Kuala_Lumpur" },
  { name: "Maldives", tz: "Indian/Maldives" },
  { name: "Malta", tz: "Europe/Malta" },
  { name: "Mexico", tz: "America/Mexico_City" },
  { name: "Moldova", tz: "Europe/Chisinau" },
  { name: "Monaco", tz: "Europe/Monaco" },
  { name: "Mongolia", tz: "Asia/Ulaanbaatar" },
  { name: "Morocco", tz: "Africa/Casablanca" },
  { name: "Myanmar", tz: "Asia/Yangon" },
  { name: "Namibia", tz: "Africa/Windhoek" },
  { name: "Nepal", tz: "Asia/Kathmandu" },
  { name: "Netherlands", tz: "Europe/Amsterdam" },
  { name: "New Zealand", tz: "Pacific/Auckland" },
  { name: "Nicaragua", tz: "America/Managua" },
  { name: "Nigeria", tz: "Africa/Lagos" },
  { name: "North Korea", tz: "Asia/Pyongyang" },
  { name: "Norway", tz: "Europe/Oslo" },
  { name: "Oman", tz: "Asia/Muscat" },
  { name: "Pakistan", tz: "Asia/Karachi" },
  { name: "Panama", tz: "America/Panama" },
  { name: "Papua New Guinea", tz: "Pacific/Port_Moresby" },
  { name: "Paraguay", tz: "America/Asuncion" },
  { name: "Peru", tz: "America/Lima" },
  { name: "Philippines", tz: "Asia/Manila" },
  { name: "Poland", tz: "Europe/Warsaw" },
  { name: "Portugal", tz: "Europe/Lisbon" },
  { name: "Qatar", tz: "Asia/Qatar" },
  { name: "Romania", tz: "Europe/Bucharest" },
  { name: "Russia (Kaliningrad)", tz: "Europe/Kaliningrad" },
  { name: "Russia (Moscow)", tz: "Europe/Moscow" },
  { name: "Russia (Samara)", tz: "Europe/Samara" },
  { name: "Russia (Vladivostok)", tz: "Asia/Vladivostok" },
  { name: "Saudi Arabia", tz: "Asia/Riyadh" },
  { name: "Senegal", tz: "Africa/Dakar" },
  { name: "Serbia", tz: "Europe/Belgrade" },
  { name: "Singapore", tz: "Asia/Singapore" },
  { name: "Slovakia", tz: "Europe/Bratislava" },
  { name: "Slovenia", tz: "Europe/Ljubljana" },
  { name: "South Africa", tz: "Africa/Johannesburg" },
  { name: "South Korea", tz: "Asia/Seoul" },
  { name: "Spain", tz: "Europe/Madrid" },
  { name: "Sri Lanka", tz: "Asia/Colombo" },
  { name: "Sweden", tz: "Europe/Stockholm" },
  { name: "Switzerland", tz: "Europe/Zurich" },
  { name: "Taiwan", tz: "Asia/Taipei" },
  { name: "Tanzania", tz: "Africa/Dar_es_Salaam" },
  { name: "Thailand", tz: "Asia/Bangkok" },
  { name: "Trinidad and Tobago", tz: "America/Port_of_Spain" },
  { name: "Tunisia", tz: "Africa/Tunis" },
  { name: "Turkey", tz: "Europe/Istanbul" },
  { name: "UAE (Dubai)", tz: "Asia/Dubai" },
  { name: "Uganda", tz: "Africa/Kampala" },
  { name: "Ukraine", tz: "Europe/Kyiv" },
  { name: "UK (London)", tz: "Europe/London" },
  { name: "Uruguay", tz: "America/Montevideo" },
  { name: "USA (Anchorage)", tz: "America/Anchorage" },
  { name: "USA (Chicago)", tz: "America/Chicago" },
  { name: "USA (Denver)", tz: "America/Denver" },
  { name: "USA (Honolulu)", tz: "Pacific/Honolulu" },
  { name: "USA (Los Angeles)", tz: "America/Los_Angeles" },
  { name: "USA (New York)", tz: "America/New_York" },
  { name: "USA (Phoenix)", tz: "America/Phoenix" },
  { name: "UTC", tz: "Etc/UTC" },
  { name: "Venezuela", tz: "America/Caracas" },
  { name: "Vietnam", tz: "Asia/Ho_Chi_Minh" },
  { name: "Zambia", tz: "Africa/Lusaka" },
  { name: "Zimbabwe", tz: "Africa/Harare" },
].sort((a, b) => a.name.localeCompare(b.name));